dist: trusty
sudo: required
language: python
python:
- 3.6.1
addons:
  apt:
    packages:
    - libcups2-dev
services:
- mysql
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
branches:
  only:
  - develop
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install flake8
- pip install coveralls
before_script:
- flake8 bcpp_subject
- mysql -e 'create database edc character set utf8;'
script:
- coverage run --source=cancer_subject manage.py test
after_success:
- coveralls
